apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
  namespace: dev
  labels:
    app: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: amardeep245/food:dev
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: ecomm
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

