apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
  namespace: dev
  labels:
    app: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: amardeep245/food:dev
        ports:
        - containerPort: 80


