apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: food
spec:
  # 1 Pod should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: food
    spec:
      containers:
      - name: food
        # Run this image
        image: amardeep245/food
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Deployment instance
  name: food
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: food

